---
- name: Set fact for v
  ansible.builtin.set_fact:
    v : 1
- name: intf conf
  cisco.ios.l3_interfaces:
    config:
      - name: "{{ intf_name }}"
        ipv4:
          - address: "{{ intf_ip }}"
    state: merged
  register: l3_config_output
  notify:
    - ip change post action

- name: Print Output data
  ansible.builtin.debug:
    msg: "{{ l3_config_output }}" 